# Etapa 1: Construir o código React
FROM node:16 AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . ./
RUN npm run build

# Etapa 2: Servir a aplicação com Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

# Expor a porta 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
